name: .NET and First Interaction

on:
  push:
    branches: [ "dbDevelopment" ]
  pull_request:
    branches: [ "dbDevelopment" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  first-interaction:
    runs-on: ubuntu-latest

    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Thank you for opening your first issue in this repository! We value your contribution.
          pr-message: >
            Thank you for submitting your first pull request! We appreciate your effort.
